# Generated by Django 5.1 on 2024-08-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_libcode_alter_visit_visitdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibCode',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
