# Generated by Django 5.1 on 2024-08-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_delete_libcode_delete_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libraryname', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
            ],
        ),
    ]
